### ISSUE TITLE
the pep470 utility needs installation instructions...

### ISSUE THREAD

**Issue by vernondcole** [pypa/pep470#1]
The email I received indicated that there was an easy to use utility: "simply execute the pep470 CLI utility".  This may in fact be simple, after said utility is installed.  I have tried two ways to install the utility, (copying the source of cli.py, and cloning the GIT repository and running setup.py install) but neither resulted in a runnable utility.  I am using Ubuntu 15.10.  I assume that this would be even worse if I were running Windows (where is the "twine" utility then?)  

Please include instructions on how to install "pep470".

**Comment by ThomasWaldmann** [comment]
I used virtualenv and pip install pep470 and the utility starts.
As it didn't really do something, I had to upgrade pip in my virtualenv to fix that:
pip install -U pip
